/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCUL_H_RPCGEN
#define _CALCUL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operandes {
	float x;
	float y;
};
typedef struct operandes operandes;

#define MATH_CALCUL 0x20000002
#define MATH_VERSION_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define PUISS2 1
extern  int * puiss2_1(int *, CLIENT *);
extern  int * puiss2_1_svc(int *, struct svc_req *);
#define MULTIXY 2
extern  float * multixy_1(operandes *, CLIENT *);
extern  float * multixy_1_svc(operandes *, struct svc_req *);
extern int math_calcul_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PUISS2 1
extern  int * puiss2_1();
extern  int * puiss2_1_svc();
#define MULTIXY 2
extern  float * multixy_1();
extern  float * multixy_1_svc();
extern int math_calcul_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operandes (XDR *, operandes*);

#else /* K&R C */
extern bool_t xdr_operandes ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCUL_H_RPCGEN */
