/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcul.h"


void
math_calcul_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  puiss2_1_arg;
	float  *result_2;
	operandes  multixy_1_arg;

#ifndef	DEBUG
	clnt = clnt_create ("kali", MATH_CALCUL, MATH_VERSION_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror ("kali");
		exit (1);
	}
#endif	/* DEBUG */
	puiss2_1_arg=6;

	result_1 = puiss2_1(&puiss2_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	multixy_1_arg.x=15; 
	multixy_1_arg.y=10;

	result_2 = multixy_1(&multixy_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}
int main(){
CLIENT *client;
operandes param; 
float *resultat;
int n,*p; 
client = clnt_create("kali", MATH_CALCUL, MATH_VERSION_1, "udp");
if (client == NULL) {
perror(" erreur creation client\n");
exit(1);
}
param.x=12;  param.y=20; 
resultat = multixy_1(&param, client);
printf(" resultat =   %f \n", *resultat);
n=16; 
p=puiss2_1(&n,client);
     printf(" 2 puissance 16 =   %d \n", *p);

}






int
mainA (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	math_calcul_1 ("kali");
exit (0);
}
