/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcul.h"

int *
puiss2_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result=2;
	for(int i=0;i<*argp;i++)
		result=result*2;
	return &result;
}

float *
multixy_1_svc(operandes *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result=argp->x * argp->y;

	return &result;
}
