/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calcul.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

complex *
addition_1(operandes *argp, CLIENT *clnt)
{
	static complex clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ADDITION,
		(xdrproc_t) xdr_operandes, (caddr_t) argp,
		(xdrproc_t) xdr_complex, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

complex *
multi_1(operandes *argp, CLIENT *clnt)
{
	static complex clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MULTI,
		(xdrproc_t) xdr_operandes, (caddr_t) argp,
		(xdrproc_t) xdr_complex, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
