/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calcul.h"

bool_t
xdr_complex (XDR *xdrs, complex *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operandes (XDR *xdrs, operandes *objp)
{
	register int32_t *buf;

	 if (!xdr_complex (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_complex (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}
